source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target '0609ButtonDemo' do
    pod 'SnapKit', '~> 5.0.0'
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
end
